#!/bin/bash

BASEDIR=$(dirname $0)
rm -rf /tmp/ppcweb.tgz
cd $BASEDIR/..
tar cvzf /tmp/ppcweb.tgz web
scp -i ~/ec2-webserver.pem /tmp/ppcweb.tgz ubuntu@ssh.swanpp.com:/home/ubuntu
ssh -i ~/ec2-webserver.pem  ubuntu@ssh.swanpp.com "rm -rf /home/ubuntu/web"
ssh -i ~/ec2-webserver.pem  ubuntu@ssh.swanpp.com "cd /home/ubuntu/; tar xzf ppcweb.tgz"
ssh -i ~/ec2-webserver.pem  ubuntu@ssh.swanpp.com "sudo rm -rf /var/www/html.bak; sudo mv /var/www/html/ /var/www/html.bak; sudo mv /home/ubuntu/web /var/www/html"
